# spring.application.name=transaction-service
server:
  port: 1003

spring:
  application:
    name: transaction-service
  data:
    mongodb:
      uri: mongodb+srv://chxxlk:WebService@clusterws.kvpkfch.mongodb.net/
      database: mobile_banking_transactions
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true