# spring.application.name=payment-service
server:
  port: 1004

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mobile_banking_payments
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true