# spring.application.name=api_gateway
server:
  port: 1001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/users/**, /auth/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
