# spring.application.name=eureka_server
server:
  port: 1000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:1000/eureka/