# spring.application.name=user_service
server:
  port: 1002

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/mobile_banking_users?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true
